version: "3.9"

services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wp"
      MYSQL_PASSWORD: "wp"
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:6.9.1-php8.3-apache
    restart: always
    depends_on:
      - db
    ports:
      - "8088:80"
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: "wp"
      WORDPRESS_DB_PASSWORD: "wp"
      WORDPRESS_DB_NAME: "wordpress"
    volumes:
      - ./wp_data:/var/www/html
      - ./woocommerce/plugin/trunk:/var/www/html/wp-content/plugins/zeno-crypto-payment-gateway
      - ./easy-digital-downloads/plugin/trunk:/var/www/html/wp-content/plugins/zeno-crypto-checkout-for-easy-digital-downloads

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    depends_on:
      - db
    ports:
      - "8089:80"
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "root"

volumes:
  db_data:
    name: zenobank_wordpress_db_data
